server:
  port: 8080

spring:
  application:
    name: mall-tiny-06
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    url: jdbc:mysql://localhost:3306/mall?characterEncoding=utf-8&useTimeZone=UTC&serverTimezone=GMT%2B8
    username: root
    password: root
logging:
  level:
    com.yqz.pth: debug
  file:
    path: E:/idea-workspace/log

jwt:
  tokenHeader: Authorization
  tokenHead: Bearer
  secret: mySecret
  expiration: 86400
mybatis:
  mapper-locations:
    - classpath*:com/**/mapper/*.xml
    - classpath:mapper/*.xml
