server:
  port: 8088

spring:
  application:
    name: mall-tiny-08
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    url: jdbc:mysql://localhost:3306/mall?characterEncoding=utf-8&useTimeZone=UTC&serverTimezone=GMT%2B8
    username: root
    password: root
  data:
    mongodb:
      host: localhost
      port: 27017
      database: mall-port
#  data:
#    elasticsearch:
#      repositories:
#        enabled: true
#      cluster-nodes: 127.0.0.1:9300
#      cluster-name: elasticsearch
#      properties:
#        path:
#          home: D:/ProgramApp/ElasticSearch/indexRepository
#        transport:
#          tcp:
#            connect_timeout: 120s

mybatis:
  mapper-locations:
    - classpath:mapper/*.xml
    - classpath*:com/**/mapper/*.xml
logging:
  level:
   com.yqz.zzh.elasticsearch: debug
  file:
    path: E:/idea-workspace/log
