server:
  port: 8080

spring:
  application:
    name: mall-tiny-04
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    url: jdbc:mysql://localhost:3306/mall?characterEncoding=utf-8&serverTimezone=UTC
    username: root
    password: root
  redis:
    host: localhost
    port: 6379
    database: 0
    password: 123456
    jedis:
      pool:
        min-idle: 0
        max-wait: -1ms
        max-idle: 8
        max-active: 8
    timeout: 3000ms

mybatis:
  mapper-locations:
    - classpath*:com/**/mapper/*.xml
    - classpath:mapper/*.xml
logging:
  file:
    path: E:/idea-workspace/log
  level:
    com.yqz.pth: debug

redis:
  key:
    prefix:
      authCode: "portal:authCode:"
    expired:
      authCode: 120 # 验证码超期时间
jwt:
  tokenHeader: Authorization #JWT存储的请求头
  secret: mySecret #JWT加解密使用的密钥
  expiration: 86400 #JWT的超期限时间(60*60*24)
  tokenHead: Bearer  #JWT负载中拿到开头
