server:
  port: 8089

spring:
  application:
    name: mall-tiny-08
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    url: jdbc:mysql://localhost:3306/mall?characterEncoding=utf-8&useTimeZone=UTC&serverTimezone=GMT%2B8
    username: root
    password: root
  rabbitmq:
    host: localhost
    port: 5672
    virtual-host: /mall
    username: mall
    password: mall
    publisher-confirms: true #如果对异步消息需要回调要设置为true

#  数据文件数据库 用于crud商品历史记录
#  data:
#    mongodb:
#      host: localhost
#      port: 27017
#      database: mall-port
# 搜索引擎
#  data:
#    elasticsearch:
#      repositories:
#        enabled: true
#      cluster-nodes: 127.0.0.1:9300
#      cluster-name: elasticsearch
#      properties:
#        path:
#          home: D:/ProgramApp/ElasticSearch/indexRepository
#        transport:
#          tcp:
#            connect_timeout: 120s

mybatis:
  mapper-locations:
    - classpath:mapper/*.xml
    - classpath*:com/**/mapper/*.xml
logging:
  level:
   com.yqz.zzh.elasticsearch: debug
  file:
    path: E:/idea-workspace/log

